kind: pipeline
type: docker
name: Docker image build

trigger:
  branch:
    - master

    
steps:
  - name: config
    image: alpine
    commands:
      - echo -n "$VERSION,latest" > .tags
      - sed -i -E "s/var_FRP_VERSION/$FRP_VERSION/" Dockerfile
      - apk add openssl
      - ./gen_uploads.sh

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/rainloop

  - name: upload
    image: plugins/s3
    settings:
      bucket: 3bd6b2ce5101e791b665d709aa8518ce
      access_key:
        from_secret: s3_username
      secret_key:
        from_secret: s3_password
      source: ./uploads/*
      target: config/
