kind: pipeline
type: docker
name: Docker image build

trigger:
  branch:
    - master

environment:
  VERSION: 1.4.2
    
steps:
  - name: config
    image: alpine
    commands:
      - echo -n "$VERSION,latest" > .tags
      - sed -i -E "s/var_VERSION/$VERSION/" Dockerfile
      - apk add openssl
      - chmod +x ./gen_upload.sh
      - ./gen_upload.sh

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/d2ray

  - name: upload
    image: plugins/s3
    settings:
      bucket: 3bd6b2ce5101e791b665d709aa8518ce
      access_key:
        from_secret: s3_username
      secret_key:
        from_secret: s3_password
      source: uploads/*
      target: config/
      strip_prefix: uploads/
      region: us-west-1
