kind: pipeline
type: docker
name: Docker image build

trigger:
  branch:
    - master
    
steps:
  - name: prep
    image: alpine
    commands:
      - sh ./ci_prep.sh

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/d2ray
  
  - name: reload
    image: alpine
    commands:
      - sh ./ci_reload.sh
