version: '3.0'

networks:
        br-d2ray:
                external: false

services:
        watchtower:
                container_name: d2ray_watchtower
                restart: unless-stopped
                image: containrrr/watchtower
                networks:
                        - br-d2ray
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
        d2ray:
                container_name: d2ray
                image: quackerd/d2ray
                restart: unless-stopped
                networks:
                        - br-d2ray
                environment:
                        - FQDN=var_hostname
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - ./config:/opt/config
                        - ./config.json:/opt/config.json
                depends_on:
                        - d2ray_nextcloud

        d2ray_nextcloud:
                container_name: d2ray_nextcloud
                image: nextcloud/nextcloud
                networks:
                        - br-d2ray
                restart: unless-stopped
                environment:
                        - SQLITE_DATABASE=nextcloud
                        - NEXTCLOUD_ADMIN_USER=fgjhgthtrhha
                        - NEXTCLOUD_ADMIN_PASSWORD=fhrh5hhdsf876713gc7821974t5t65gg
                        - NEXTCLOUD_TRUSTED_DOMAINS=*
